### ISSUE TITLE
Vue.js Berlin is not visible 

### ISSUE THREAD

**Issue by sedrickcz** [OpnTec/2018.opentechsummit.de#6]
Vue.js Berlin title is white and therefore really poorly visible on gray and white background.

<img width="702" alt="screen shot 2018-04-25 at 10 35 20" src="https://user-images.githubusercontent.com/1304885/39234786-8c66fbd8-4874-11e8-84c0-91e64df6f773.png">

**Comment by maxlorenz** [comment]
Duplicate of issue 4? See PR

**Comment by mariobehling** [comment]
Was solved.
