### ISSUE TITLE
Button in schedule area has orange font instead of white

### ISSUE THREAD

**Issue by mariobehling** [OpnTec/2018.opentechsummit.de#8]
Please make color of font white.
![screenshot from 2018-05-07 16-28-09](https://user-images.githubusercontent.com/1583873/39707142-d069e7de-5213-11e8-9501-e7e360e982d7.png)

**Comment by MadhavBahl** [comment]
Is this issue still open? 

If yes, can I work on this?

**Comment by mariobehling** [comment]
Yes, please go ahead.

**Comment by MadhavBahl** [comment]
Hey, @mariobehling, the font-color is already white: 

![image](https://user-images.githubusercontent.com/26179770/45941368-6eb74080-bffb-11e8-9caf-22badaa744b5.png)

This issue can be closed.
